# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Metal Infestus
email: metalinfestus@gmail.com
description: A catedral do metal
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://metalinfestus.com"
source: ./
timezone: Europe/Lisbon
github: [metadata]

# Build settings
remote_theme: dieghernan/chulapa

plugins:
  - jekyll-include-cache

chulapa-skin:
  skin: gitdev-dark
  vars:
    footer-chulapa-bg-color: "#202020"

defaults:
  - scope:
      path: ""
    values:
      layout: default

navbar:
  style: dual
  brand:
    title: Início
    img: "./assets/images/skull.png"
    url: /
  nav:
    - title: Bilhetes
      url: /tickets
    - title: Localização
      url: /location
    - title: Sobre
      url: /about
    - title: Contactos
      url: /contacts

footer:
  links:
    - label: Instagram
      icon: fab fa-instagram
      url: https://www.instagram.com/metalinfestus?igsh=MWRyb2l4bmw5emVkdQ==
    - label: Facebook
      icon: fab fa-facebook
      url: https://www.facebook.com/share/f9pCe6LY77ujbeLJ/
    - label: Email
      icon: fa-regular fa-envelope
      url: "info@metalinfestus.com"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
